// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *link_tree → Links*
 */
export interface LinkTreeDocumentDataLinksItem {
  /**
   * label field in *link_tree → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * url field in *link_tree → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *link_tree → icons*
 */
export interface LinkTreeDocumentDataIconsItem {
  /**
   * icon field in *link_tree → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.icons[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * rede_social field in *link_tree → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.icons[].rede_social
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  rede_social: prismic.KeyTextField;

  /**
   * url field in *link_tree → icons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.icons[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for link_tree documents
 */
interface LinkTreeDocumentData {
  /**
   * Foto de perfil field in *link_tree*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Nome field in *link_tree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome
   * - **API ID Path**: link_tree.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Bio field in *link_tree*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * Links field in *link_tree*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<LinkTreeDocumentDataLinksItem>>;

  /**
   * icons field in *link_tree*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tree.icons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  icons: prismic.GroupField<Simplify<LinkTreeDocumentDataIconsItem>>;
}

/**
 * link_tree document from Prismic
 *
 * - **API ID**: `link_tree`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinkTreeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LinkTreeDocumentData>,
    "link_tree",
    Lang
  >;

type LinktreeDocumentDataSlicesSlice = LinkTreeSlice;

/**
 * Content for LinkTree documents
 */
interface LinktreeDocumentData {
  /**
   * Slice Zone field in *LinkTree*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LinktreeDocumentDataSlicesSlice>; /**
   * Meta Title field in *LinkTree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: linktree.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *LinkTree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: linktree.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *LinkTree*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * LinkTree document from Prismic
 *
 * - **API ID**: `linktree`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinktreeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LinktreeDocumentData>,
    "linktree",
    Lang
  >;

export type AllDocumentTypes = LinkTreeDocument | LinktreeDocument;

/**
 * Primary content in *LinkTree → Default → Primary*
 */
export interface LinkTreeSliceDefaultPrimary {
  /**
   * teste field in *LinkTree → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Teste
   * - **API ID Path**: link_tree.default.primary.teste
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  teste: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for LinkTree Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinkTreeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkTreeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkTree*
 */
type LinkTreeSliceVariation = LinkTreeSliceDefault;

/**
 * LinkTree Shared Slice
 *
 * - **API ID**: `link_tree`
 * - **Description**: LinkTree
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinkTreeSlice = prismic.SharedSlice<
  "link_tree",
  LinkTreeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LinkTreeDocument,
      LinkTreeDocumentData,
      LinkTreeDocumentDataLinksItem,
      LinkTreeDocumentDataIconsItem,
      LinktreeDocument,
      LinktreeDocumentData,
      LinktreeDocumentDataSlicesSlice,
      AllDocumentTypes,
      LinkTreeSlice,
      LinkTreeSliceDefaultPrimary,
      LinkTreeSliceVariation,
      LinkTreeSliceDefault,
    };
  }
}
